# Generated by Django 3.2.5 on 2021-09-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_ad_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
