# Generated by Django 3.2.5 on 2021-09-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210923_1825'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['title'], name='main_table_title_9e50c5_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['quantity'], name='main_table_quantit_0ab6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['distance'], name='main_table_distanc_4742df_idx'),
        ),
    ]
